name: Build api

on:
  push:
    branches: [ "master" ]

jobs:

  docker:

    runs-on: ubuntu-latest
    
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          push: true
          tags: nemanjaaas99/intens-praksa:latest
